general:
  debug: false
stats:
  configversion: ${project.config.version}
  database:
    type: "sqlite"
    host: "localhost"
    username: "Beardstats"
    password: "changeme"
    database: "stats"
    table: "stats"
    port: 3306
  blacklist:
    - creative
    - tutorialIsland
  pages:
    default:
      - "blocks placed:stats.totalblockcreate"
      - "blocks broken:stats.totalblockdestroy"
      - "kills:kills.total"
      - "deaths:deaths.total"
      - "killdeath:comp.kd"
    archery:
      - "total shots:bow.shots"
      - "fire shots:bow.fireshots"
      - "Epirus bow shots:bow.infiniteshots"
customstats:
  - "comp.kd = $kills.total - $deaths.total"
savedcustomstats:
  - "comp.pk = $kills.player - $deaths.player"
customformats:
  - "stats.move:%1$s metres" 
