stats:
  database:
    type: "file"
    host: "localhost"
    username: "Beardstats"
    password: "changeme"
    database: "stats"
  worlds:
    - creative
    - tutorialIsland
  pages:
    default:
      "blocks placed": "stats.totalblockcreate"
      "blocks broken": "stats.totalblockdestroy"
      kills: "kills.total"
      deaths: "deaths.total"