name: BeardStat
main: me.tehbeard.BeardStat.BeardStat
version: ${project.plugin.version}-${describe}
authors: [Tehbeard]
commands:
    stats:
        description: Show stats about yourself or another player
        usage: /stats [stats]...
        aliases: [bstats]
        permission: stat.command.stat
    played:
        description: Show play time for you or another player
        usage: /played [player]
        aliases: [bplayed]
        permission: stat.command.played
    statpage:
        description: View the various stats pages
        usage: /statpage [page]
        aliases: [bstatpage]
    laston:
        description: View last time a player was on
        usage: /laston [player]
        aliases: [blaston]

        
permissions:
  stat.*:
    description: Allows use of all stat commands
    default: op
    children:
      stat.command.stat: true
      stat.command.played: true
      stat.command.played.other: true
      stat.command.stat.other: true
      stat.command.laston: true
  stat.players:
    description: Allows use of all stat commands
    default: true
    children:
      stat.command.stat: true
      stat.command.played: true
            
  stat.command.stat:
    description: View your own stats
  stat.command.stat.other:
    description: View other's stats
    default: op
  stat.command.played:
    description: Allows you to view your /played
  stat.command.played.other:
    description: See how much others have played
    default: op
  stat.command.laston:
    description: View when a player was last online
    default: op

    
