name: BeardStat
main: me.tehbeard.BeardStat.BeardStat
version: 0.1
depend: [Permissions]
commands:
    stats:
        description: Show stats about yourself
        usage: /stats [stats]...
    statsother:
        description: Show stats about others
        usage: /statsother [Player] [stats]...
    played:
        description: Show play time
        usage: /played
    playedother:
        description: Show play time of other
        usage: /playedother [Player]
    statsget:
        description: Show stats for an offline player
        usage: /statsget [Player] [stats]...